
import type { Metadata } from "next";
import "../globals.css";
import Footer from "../shared/components/Footer";
import Nav from "../shared/ui/Nav";
export const metadata: Metadata = {
  title: "Login Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main className="test">
        <Nav />
        {children}
        <Footer />
      </main>
  );
}
