
import type { Metadata } from "next";
import "../globals.css";
import DashNav from "./dash_nav";
import Sidebar from "./side";
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main className="bg-[#081028] ">
        <DashNav/>
        <div className="flex mx-auto container justify-between">
          <div className="">
        <Sidebar/>
          </div>
          <div className="w-full">
        {children}
          </div>
        </div>
      </main>
  );
}
